name: NodeJS with express

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    container: node:20

    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: node app.js
        
